# Generated by Django 4.2.19 on 2025-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_refundable_wallet_deposit',
            field=models.BooleanField(default=False, help_text='Mark this asset as a refundable wallet deposit item.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='max_order_per_partner',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Set a limit if this asset should have a max order restriction per partner.', null=True),
        ),
    ]
