# Generated by Django 5.2.6 on 2025-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_category_asset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Banner Title', max_length=150)),
                ('description', models.TextField(blank=True, default='This is a default banner description.', null=True)),
                ('image', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=1, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
