# Generated by Django 4.2.19 on 2025-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_is_refundable_wallet_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Required size: 240 × 240 pixels (JPG/PNG only) ', null=True, upload_to='categories/images/'),
        ),
    ]
