# Generated by Django 4.2.19 on 2025-11-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAssetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Unknown', max_length=255)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('skyid', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitemserial')),
            ],
        ),
    ]
