# Generated by Django 4.2.19 on 2025-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerassetmapping',
            name='skyid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
