# Generated by Django 4.2.19 on 2025-11-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customermapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerassetmapping',
            options={'verbose_name': 'Customer Device Mapping', 'verbose_name_plural': 'Customer Device Mappings'},
        ),
    ]
