"""
Django settings for pims project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

API_BASE_URL = config("API_BASE_URL")
API_AUTH_USERNAME = config("API_AUTH_USERNAME")
API_AUTH_PASSWORD = config("API_AUTH_PASSWORD")

print("🔍 API_BASE_URL:", os.getenv("API_BASE_URL"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8wsq-%k%c_kzb^@c#tzlx25)ed2q))2@=74z6_4o4#svb4p0zt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'partner',
    'store',
    'asset',
    'order',
    'customermapping',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pims.urls'
AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'  # Redirect after login
LOGOUT_REDIRECT_URL = 'login'

RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pims.wsgi.application'




# # Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'developer@skylink.net.in'
# EMAIL_HOST_PASSWORD = 'vrghuycfaljvjobi'

# DEFAULT_FROM_EMAIL = 'developer@skylink.net.in'

# EMAIL_SUBJECT_PREFIX = '[SKYLINK] '




# ZeptoMail Configuration
ZEPTOMAIL_API_URL = "https://api.zeptomail.in/v1.1/email"
ZEPTOMAIL_API_KEY = "PHtE6r0NRe3oj2Z6oRYH5/SwR5OsM4h7/O82JFFG5ohFDqRWHk0Dq40tkzPmo0sjAPlEEaLOy9pssejKseKBIme4N2saWmqyqK3sx/VYSPOZsbq6x00YuFUSdkffUILuc9Vi3CTUud3aNA=="
ZEPTOMAIL_FROM_EMAIL = "info@skylink.net.in"

EMAIL_BACKEND = "accounts.zeptomail_backend.ZeptoMailBackend"

DEFAULT_FROM_EMAIL = "info@skylink.net.in"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pims',     # Database name (same as you created in pgAdmin)
        'USER': 'postgres',           # Default PostgreSQL user
        'PASSWORD': 'Admin@123',  # Password you set during installation
        'HOST': 'localhost',          # Database host
        'PORT': '5433',               # Default PostgreSQL port
    }
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'pims',     # Database name (same as you created in pgAdmin)
#         'USER': 'postgres',           # Default PostgreSQL user
#         'PASSWORD': 'postgres',  # Password you set during installation
#         'HOST': 'localhost',          # Database host
#         'PORT': '5432',               # Default PostgreSQL port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
JAZZMIN_SETTINGS = {
    "site_title": "PIMS Admin",
    "site_header": "PIMS Admin Panel",
    "welcome_sign": "Welcome to PIMS Dashboard",
    "site_brand": "Skyplay ISP Store",

    # 🖼️ Logo & Favicon
    "site_logo": "images/logo.png",          # top-left logo in header
    "login_logo": "images/logo.png",         # logo on login screen
    "site_icon": "images/favicon.ico",        # optional (makes it rounded)

    # 🔍 Search model
    "search_model": "auth.User",

    # 🔗 Top menu links
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "/admin/", "permissions": ["auth.view_user"]},
    ],

    # ✅ Sidebar behavior
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": [],
    "hide_models": [],

    # 🎨 Optional: add your own CSS for more control
    "custom_css": "css/jazzmin_custom.css",

    
    "custom_apps": {
        "auth": {
            "name": "Groups",     # 👈 New name in sidebar
            "icon": "fas fa-users-cog",
        },
    }
}


