# Generated by Django 4.2.19 on 2025-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitemserial_mac_id_orderitemserial_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemserial',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
