# Generated by Django 4.2.19 on 2025-10-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitemserial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='serial_number',
        ),
    ]
