# Generated by Django 4.2.19 on 2025-10-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Transit'), (2, 'Received')], default=0),
        ),
    ]
