# Generated by Django 4.2.19 on 2025-10-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_shipping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipping_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Transit'), (2, 'Delivered'), (3, 'Returned')], default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Shipment',
                'verbose_name_plural': 'Order Shipments',
            },
        ),
    ]
