# Generated by Django 4.2.19 on 2025-10-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordershipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
