# Generated by Django 4.2.19 on 2025-10-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='signature',
            new_name='order_confirmed_signature',
        ),
    ]
