# Generated by Django 4.2.19 on 2025-10-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_signature_order_order_confirmed_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_confirmed_signature',
        ),
    ]
