# Generated by Django 4.2.19 on 2025-10-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_order_confirmed_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
