# Generated by Django 4.2.19 on 2025-11-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=50)),
                ('last_name', models.CharField(default='Doe', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('refundable_wallet', models.DecimalField(decimal_places=2, default=0.0, help_text='Refundable wallet balance for this partner', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner Category',
                'verbose_name_plural': 'Partner Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('transaction_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='partner.partner')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_category',
            field=models.ForeignKey(blank=True, help_text='Category of the partner (e.g., Platinum, Gold, Silver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partner.partnercategory'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnerCategoryAssetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_limit', models.PositiveIntegerField(default=0, help_text='Default maximum quantity for this asset based on category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset for which the limit applies.', on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='asset.asset')),
                ('partner_category', models.ForeignKey(help_text='Partner category for which this limit applies.', on_delete=django.db.models.deletion.CASCADE, related_name='asset_limits', to='partner.partnercategory')),
            ],
            options={
                'verbose_name': 'Partner Category Asset Limit',
                'verbose_name_plural': 'Partner Category Asset Limits',
                'ordering': ['partner_category__name', 'asset__name'],
                'unique_together': {('partner_category', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='PartnerAssetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_purchase_limit', models.PositiveIntegerField(default=0, help_text='Maximum quantity of this asset that the partner can purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_limits', to='asset.asset')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_limits', to='partner.partner')),
            ],
            options={
                'verbose_name': 'Partner Asset Limit',
                'verbose_name_plural': 'Partner Asset Limits',
                'unique_together': {('partner', 'asset')},
            },
        ),
    ]
