# Generated by Django 5.2.6 on 2025-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='refundable_wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Refundable wallet balance for this partner', max_digits=10),
        ),
    ]
