# Generated by Django 4.2.19 on 2025-11-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
