# Generated by Django 4.2.19 on 2025-10-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_is_refundable_wallet_deposit_and_more'),
        ('partner', '0002_partner_refundable_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAssetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_purchase_limit', models.PositiveIntegerField(default=0, help_text='Maximum quantity of this asset that the partner can purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_limits', to='asset.asset')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_limits', to='partner.partner')),
            ],
            options={
                'verbose_name': 'Partner Asset Limit',
                'verbose_name_plural': 'Partner Asset Limits',
                'unique_together': {('partner', 'asset')},
            },
        ),
    ]
