# Generated by Django 4.2.19 on 2025-11-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partnerassetlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_category',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver')], default='silver', help_text='Category of the partner (Platinum, Gold, Silver)', max_length=10),
        ),
    ]
