# Generated by Django 4.2.19 on 2025-11-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_partner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partner Category',
                'verbose_name_plural': 'Partner Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_category',
            field=models.ForeignKey(blank=True, help_text='Category of the partner (e.g., Platinum, Gold, Silver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partner.partnercategory'),
        ),
    ]
