# Generated by Django 4.2.19 on 2025-11-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_asset_is_refundable_wallet_deposit_and_more'),
        ('partner', '0005_partnercategory_alter_partner_partner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategoryAssetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_limit', models.PositiveIntegerField(default=0, help_text='Default maximum quantity for this asset based on category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset for which the limit applies.', on_delete=django.db.models.deletion.CASCADE, related_name='category_limits', to='asset.asset')),
                ('partner_category', models.ForeignKey(help_text='Partner category for which this limit applies.', on_delete=django.db.models.deletion.CASCADE, related_name='asset_limits', to='partner.partnercategory')),
            ],
            options={
                'verbose_name': 'Partner Category Asset Limit',
                'verbose_name_plural': 'Partner Category Asset Limits',
                'ordering': ['partner_category__name', 'asset__name'],
                'unique_together': {('partner_category', 'asset')},
            },
        ),
    ]
